from enum import Enum

class Format(Enum):
    STANDARD = "standard"
    FUTURE = "future"
    HISTORIC = "historic"
    TIMELESS = "timeless"
    GLADIATOR = "gladiator"
    PIONEER = "pioneer"
    MODERN = "modern"
    LEGACY = "legacy"
    PAUPER = "pauper"
    VINTAGE = "vintage"
    PENNY = "penny"
    COMMANDER = "commander"
    OATHBREAKER = "oathbreaker"
    STANDARD_BRAWL = "standardbrawl"
    BRAWL = "brawl"
    COMPETITIVE_BRAWL = "competitivebrawl"
    ALCHEMY = "alchemy"
    PAUPER_COMMANDER = "paupercommander"
    DUEL = "duel"
    OLDSCHOOL = "oldschool"
    PREMODERN = "premodern"
    PREDH = "predh"
    TLR = "tlr"